### ISSUE TITLE
Confirm that the image viewer interface works.

### ISSUE THREAD

**Issue by jimsafley** [omeka/plugin-Zoomit#1]
On items that contain more than one supported file, there should be a list of images that, when clicked, opens/updates the Zoom.it viewer.

**Comment by leeannghajar** [comment]
Tested in Firefox and Safari with tif, jpg, png. Files loaded in admin and public site and zoomit was functional. On items with more than one supported file and two file types (jpg and png), one file type was listed under zoomit on the public site. The text read "Click below to view an image using the [blank, no text] viewer."  The first image appeared in the docs viewer.  With multiple files of the same extension (png), two pf the three files associated with an item appeared listed below the  "Click below to view an image using the [blank, no text] viewer." line. http://dev.omeka.org/lghajar/testsite/items/show/12

In an instance with three files with different extensions associated with an item (jpg, pdf, docx), the jpg did not show up under zoomit.  http://dev.omeka.org/lghajar/testsite/items/show/16

**Comment by jimsafley** [comment]
I see "Zoom.it" where you indicate "[blank, no text]". Granted, the link and background colors are similar.

The first file is a TIF, which the Docs Viewer plugin will automatically display. If I recall correctly, the Zoom.it TOS stipulates that the viewer may not be opened automatically when embedded on a page. Therefore, this plugin requires the user to open the viewer directly by clicking the links.

**Comment by sheilabrennan** [comment]
works as designed for me in IE9 & FFx 17.1 for PC
