### ISSUE TITLE
Confirm that the Zoom.it viewer works for supported files.

### ISSUE THREAD

**Issue by jimsafley** [omeka/plugin-Zoomit#2]
It should only be visible on items that contain at least one file that Zoom.it supports. BMP, GIF, ICO, JPG, PNG, and TIFF files should be supported.

**Comment by leeannghajar** [comment]
Does not appear on public or admin side with  unsupported files, e.g. docx, pdf, ppt

**Comment by jimsafley** [comment]
This is expected behavior, right?

**Comment by leeannghajar** [comment]
Functions as expected.

**Comment by sheilabrennan** [comment]
Yes. Finding generally that the loading of an image in the viewer in IE is longer. Sometimes have to refresh the page for file to appear in the viewer.
