### ISSUE TITLE
Confirm that the viewer embed flags are set after upgrade.

### ISSUE THREAD

**Issue by jimsafley** [omeka/plugin-Zoomit#4]
New to this version are two configuration flags that set visibility of the image viewer in the admin and public items/show page. Make sure that these flags are set to true after upgrade.

**Comment by leeannghajar** [comment]
Didn't have this plugin before; no upgrade comparison possible.

**Comment by patrickmj** [comment]
@leeanghajar could you revert one of your installations back to 1.5, install ZoomIt, and try it out? Best to disable all the other plugins so they won't go crazy when going back and forth from 1.5 ro 2.0

**Comment by sheilabrennan** [comment]
@leeannghajar are you able to do this? I don't have time to do this test in my in-between times while I'm off this week.

**Comment by leeannghajar** [comment]
@sheilabrennan No worries, Sheila, I'm on it.
